// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "ArguMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Dev-only body attribute to match common extension-injected attribute
  const devBodyProps =
    process.env.NODE_ENV === "development" ? { "cz-shortcut-listen": "true" } : {};

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`} {...devBodyProps}>
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
